### ISSUE TITLE
Delete this repo

### ISSUE THREAD

**Issue by saad-ali** [kubernetes-csi/kubernetes-csi-migration-library#11]
Is the code in this repo used anywhere? Did it get superseded by https://github.com/kubernetes/csi-translation-lib ? If so, we should delete this repo.

CC @davidz627 @msau42

**Comment by davidz627** [comment]
supersceded by: https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/csi-translation-lib

kubernetes-csi/kubernetes-csi-migration-library should be deleted.
/approve
